// generated by mBlock5 for mBot
// codes make you happy

#include <MeMCore.h>
#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

double currentTime = 0;
double lastTime = 0;
MeLEDMatrix ledMtx_1(1);
MeUltrasonicSensor ultrasonic_3(3);
MeDCMotor motor_9(9);
MeDCMotor motor_10(10);

double getLastTime(){
  return currentTime = millis() / 1000.0 - lastTime;
}
void move(int direction, int speed) {
  int leftSpeed = 0;
  int rightSpeed = 0;
  if(direction == 1) {
    leftSpeed = speed;
    rightSpeed = speed;
  } else if(direction == 2) {
    leftSpeed = -speed;
    rightSpeed = -speed;
  } else if(direction == 3) {
    leftSpeed = -speed;
    rightSpeed = speed;
  } else if(direction == 4) {
    leftSpeed = speed;
    rightSpeed = -speed;
  }
  motor_9.run((9) == M1 ? -(leftSpeed) : (leftSpeed));
  motor_10.run((10) == M1 ? -(rightSpeed) : (rightSpeed));
}

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}

void setup() {
  pinMode(A7, INPUT);
  ledMtx_1.setColorIndex(1);
  ledMtx_1.setBrightness(6);
  while(!((0 ^ (analogRead(A7) > 10 ? 0 : 1))))
  {
    _loop();
  }
  lastTime = millis() / 1000.0;
  while(1) {
      ledMtx_1.drawStr(0, 0 + 7, String(getLastTime()).c_str());
      if((!((ultrasonic_3.distanceCm() < 25)))  &&  (getLastTime() < 5)){

          motor_9.run(-1 * 90/100.0*255);
          motor_10.run(50/100.0*255);

      }else{

          move(3, 50 / 100.0 * 255);
          _delay(0.75);
          move(3, 0);
          lastTime = millis() / 1000.0;

      }

      _loop();
  }

}

void _loop() {
}

void loop() {
  _loop();
}


